### ISSUE TITLE
Cannot locate rosdep definition for [spot_msg_interface]

### ISSUE THREAD

**Issue by Emptii** [MASKOR/webots_ros2_spot#14]
## Problem
I have tried installing the webot_spot requirements as described [here](https://maskor.fh-aachen.de/teaching/material/2023-ST_RobROS/practical/webots_spot/1_install.html#ansible-playbook).

However, after running the ansible script and running `colcon build --symlink-install` i get the following output:
```bash
Starting >>> webots_spot_msgs
Starting >>> webots_spot_teleop
/home/user/.local/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/home/user/.local/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
--- stderr: webots_spot_msgs                                                                 
CMake Error at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_write_generator_arguments.cmake:44 (message):
  rosidl_write_generator_arguments() called with unused arguments:
  INCLUDE_PATHS;action_msgs:/opt/ros/humble/share/action_msgs;builtin_interfaces:/opt/ros/humble/share/builtin_interfaces;unique_identifier_msgs:/opt/ros/humble/share/unique_identifier_msgs
Call Stack (most recent call first):
  /opt/ros/rolling/share/rosidl_generator_type_description/cmake/rosidl_generator_type_description_generate_interfaces.cmake:57 (rosidl_write_generator_arguments)
  /opt/ros/humble/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:25 (rosidl_generate_interfaces)


---
Failed   <<< webots_spot_msgs [0.76s, exited with code 1]
Aborted  <<< webots_spot_teleop [0.80s]                     

Summary: 0 packages finished [1.40s]
  1 package failed: webots_spot_msgs
  1 package aborted: webots_spot_teleop
  2 packages had stderr output: webots_spot_msgs webots_spot_teleop
  1 package not processed
```

Which made me think the webots_spot_msgs package might be faulty. 
I ran the install instructions found in the README.md, but get the following output:

```bash
$ rosdep install --ignore-src --from-paths src -y -r
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
webots_spot_teleop: Cannot locate rosdep definition for [spot_msg_interface]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```

I am using Ubuntu 22.04 btw.
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

Is something broken or am I missing something?

**Comment by skpawar1305** [comment]
> ## Problem
> I have tried installing the webot_spot requirements as described [here](https://maskor.fh-aachen.de/teaching/material/2023-ST_RobROS/practical/webots_spot/1_install.html#ansible-playbook).
> 
> However, after running the ansible script and running `colcon build --symlink-install` i get the following output:
> 
> ```shell
> Starting >>> webots_spot_msgs
> Starting >>> webots_spot_teleop
> /home/user/.local/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
>   warnings.warn(
> /home/user/.local/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
>   warnings.warn(
> --- stderr: webots_spot_msgs                                                                 
> CMake Error at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_write_generator_arguments.cmake:44 (message):
>   rosidl_write_generator_arguments() called with unused arguments:
>   INCLUDE_PATHS;action_msgs:/opt/ros/humble/share/action_msgs;builtin_interfaces:/opt/ros/humble/share/builtin_interfaces;unique_identifier_msgs:/opt/ros/humble/share/unique_identifier_msgs
> Call Stack (most recent call first):
>   /opt/ros/rolling/share/rosidl_generator_type_description/cmake/rosidl_generator_type_description_generate_interfaces.cmake:57 (rosidl_write_generator_arguments)
>   /opt/ros/humble/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
>   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
>   CMakeLists.txt:25 (rosidl_generate_interfaces)
> 
> 
> ---
> Failed   <<< webots_spot_msgs [0.76s, exited with code 1]
> Aborted  <<< webots_spot_teleop [0.80s]                     
> 
> Summary: 0 packages finished [1.40s]
>   1 package failed: webots_spot_msgs
>   1 package aborted: webots_spot_teleop
>   2 packages had stderr output: webots_spot_msgs webots_spot_teleop
>   1 package not processed
> ```
> 
> Which made me think the webots_spot_msgs package might be faulty. I ran the install instructions found in the README.md, but get the following output:
> 
> ```shell
> $ rosdep install --ignore-src --from-paths src -y -r
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> webots_spot_teleop: Cannot locate rosdep definition for [spot_msg_interface]
> Continuing to install resolvable dependencies...
> #All required rosdeps installed successfully
> ```
> 
> I am using Ubuntu 22.04 btw.
> 
> ```
> Distributor ID:	Ubuntu
> Description:	Ubuntu 22.04.3 LTS
> Release:	22.04
> Codename:	jammy
> ```
> 
> Is something broken or am I missing something?

sorry, was out for the weekend
could you please come to the lab tomorrow (Monday)? I'll take a look

also, if it's urgent, follow the old readme for now

https://github.com/MASKOR/webots_ros2_spot/blob/f138dc8f79a782e95edf0853522f456652626ca6/README.md

**Comment by Emptii** [comment]
Okay after you fixed the issues on my laptop, i was finally able to solve it on my home machine aswell.

Something was very broken with my ros installation. Following the ros2 installation did not install ros2 at all on my pc, and im guessing that was because i hab some left over packages of ros from who knows when. I did not get an error output, but the /opt/ros/setup.bash file (and i assume other files aswell) did not exists after multiple installation attempts. `apt` was sure ros2 was  installed when it was not and only ever created the `/opt/ros/humble/share` directory for some reason.

If anyone ever runs into a similar issue, here is what i did:

```bash
sudo apt-get remove ros-*
```

Note that `sudo apt-get remove ros-humble-*` was not enough in my case. Thats what i tried very early on and why I was sure I had a cleaned up all old ros versions.

Thanks for your help again @skpawar1305
