### ISSUE TITLE
Can't copy 'launch/rtabmap_launch.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by JacobJBeck** [MASKOR/webots_ros2_spot#17]
While following the instructions for install, when I run `colcon build --symlink-install` I get the following output:

```
--- stderr: webots_spot
/usr/local/lib/python3.10/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't copy 'launch/rtabmap_launch.py': doesn't exist or not a regular file
---
Failed   <<< webots_spot [1.99s, exited with code 1]
```

As the error says, this file doesn't seem to exist. It was removed in commit 61fee3f. I was unable to determine where this requirement comes from, as `setup.py` looks for `"launch/*_launch.py"`, which should not include non-existent files.

This is with ROS Humble on Ubuntu 22.04.

**Comment by skpawar1305** [comment]
hello, delete the current build and install folder before colcon build --symlink-install as that launch file was deleted

**Comment by JacobJBeck** [comment]
Yeah, that fixed it. I should have guessed :sweat:
