### ISSUE TITLE
Issues with building and rosdep

### ISSUE THREAD

**Issue by Ulfin85** [MASKOR/webots_ros2_spot#24]
When build with colcon I get this error. I'm following the instructions exactly and using the correct versions of ubuntu and 
ros2. Not sure what I'm doing wrong or if there's an issue with the installation guide. Thanks can't wait to get this working.

I'm also getting another error when running rosdep: 
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
webots_spot: Cannot locate rosdep definition for [robot_state_publisher]

Finished <<< webots_ros2_importer [2.42s]
--- stderr: webots_spot_msgs                                          
CMake Error at CMakeLists.txt:19 (find_package):
  By not providing "Findament_cmake.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ament_cmake", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake" with
  any of the following names:

    ament_cmakeConfig.cmake
    ament_cmake-config.cmake

  Add the installation prefix of "ament_cmake" to CMAKE_PREFIX_PATH or set
  "ament_cmake_DIR" to a directory containing one of the above files.  If
  "ament_cmake" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by skpawar1305** [comment]
source /opt/ros/humble/setup.bash
