### ISSUE TITLE
spotarm_link ERROR

### ISSUE THREAD

**Issue by Rhymakers** [MASKOR/webots_ros2_spot#25]
I proceeded according to the readme file, and I proceeded with the version of uuntu 22, ros2 humble, and webbot R2023b.

The following error appears in the console window when you run the ros2 launch webs_spot_launch.py command.

INFO: pedestrian: Starting controller: python3 -u pedestrian.py "--trajectory=-7.2 -1.2, -7.2 3.8" --speed=0.25
INFO: 'Ros2Supervisor' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'Ros2Supervisor'.
INFO: 'SpotArm' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'SpotArm'.
INFO: 'Spot' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'Spot'.
INFO: 'Spot' extern controller: connected.
INFO: 'SpotArm' extern controller: connected.
INFO: 'Ros2Supervisor' extern controller: connected.
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0

And is there an example code that recognizes objects and puts them in a box?

**Comment by skpawar1305** [comment]
> I proceeded according to the readme file, and I proceeded with the version of uuntu 22, ros2 humble, and webbot R2023b.
> 
> The following error appears in the console window when you run the ros2 launch webs_spot_launch.py command.
> 
> INFO: pedestrian: Starting controller: python3 -u pedestrian.py "--trajectory=-7.2 -1.2, -7.2 3.8" --speed=0.25 INFO: 'Ros2Supervisor' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'Ros2Supervisor'. INFO: 'SpotArm' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'SpotArm'. INFO: 'Spot' extern controller: Waiting for local or remote connection on port 1234 targeting robot named 'Spot'. INFO: 'Spot' extern controller: connected. INFO: 'SpotArm' extern controller: connected. INFO: 'Ros2Supervisor' extern controller: connected. WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0 WARNING: DEF Spot Spot > SpotArm "SpotArm" > HingeJoint "spotarm_link1" > Solid "spotarm_link1" > HingeJoint "spotarm_link2" > Solid "spotarm_link2" > HingeJoint "spotarm_link3" > Solid "spotarm_link3" > HingeJoint "spotarm_link4" > Solid "spotarm_link4" > SliderJoint "spotarm_link5" > Solid "spotarm_link5" > HingeJoint "spotarm_link6" > Solid "spotarm_link6" > HingeJoint "front" > TiagoGripper "front" > DEF RIGHT_GRIPPER_JOINT SliderJoint > LinearMotor "gripper_right_finger_joint": too low requested position: -1.07451e-06 < 0
> 

everything looks correct, spot should move with teleop

> And is there an example code that recognizes objects and puts them in a box?
>

yes, we've have a solution, we expect that students perform the task on their own, hence the code is private
you may refer programs in scripts folder for performing different tasks

**Comment by skpawar1305** [comment]
example
https://www.linkedin.com/posts/alert-the-fh-aachen-legged-rescue-team_whole-body-motion-planning-in-simulation-activity-7153406969851101186-NmqD?utm_source=share&utm_medium=member_desktop
