### ISSUE TITLE
Run the scripts from other repository

### ISSUE THREAD

**Issue by ToncyChen** [MASKOR/webots_ros2_spot#26]
I want to run the example scripts from [spot_ros2
/spot_examples/](https://github.com/bdaiinstitute/spot_ros2/tree/main/spot_examples) and launch `spot_launch.py`  file to run the simulation of the example scripts.
Is it possible to run the scripts from other repository in your webots simulation environment?

**Comment by skpawar1305** [comment]
they won't work directly
you may use moveit2 and nav2 to achieve similar results..

in future I can probably make those examples work directly with this simulation with some hacks,

**Comment by ToncyChen** [comment]
So is it possible to deploy in the real robot (using the ros2 interface ) any simulated (recorded) trajectories planned on Nav2 and Moveit2 using the Webots?
If it is possible, could you provide any example on how to do it?

**Comment by skpawar1305** [comment]
> So is it possible to deploy in the real robot (using the ros2 interface ) any simulated (recorded) trajectories planned on Nav2 and Moveit2 using the Webots? If it is possible, could you provide any example on how to do it?

ofcourse
we've many repositories under this organization you may refer
https://github.com/orgs/RRL-ALeRT/repositories
