### ISSUE TITLE
Using other world file

### ISSUE THREAD

**Issue by ToncyChen** [MASKOR/webots_ros2_spot#28]
I recently created my own world file and use it to replace the `spot.wbt` in `spot_launch.py`. After rebuilding the workspace and launching the `spot_launch.py`, the terminal showed the following error messages:
![Screenshot from 2024-09-09 23-09-57](https://github.com/user-attachments/assets/cbdb8dc0-de00-4b0f-bde1-438def73964b)
Is it possible to replace the `spot.wbt` with other world file and run the new environment with nav2, moveit2 successfully?
If so, could you guide me how to achieve this? 
Which configuration should I add in my new world file?
And in addition to `spot_launch.py`, what else files should I also change too?

**Comment by skpawar1305** [comment]
nav2 and moveit2 will work

for start, remove everything in following line except Spot
https://github.com/MASKOR/webots_ros2_spot/blob/016dc7136c49c0a1927d80afa22dd4c224d5714c/webots_spot/spot_driver.py#L443

**Comment by skpawar1305** [comment]
maybe you would understand better through a non ros2 version

https://github.com/RRL-ALeRT/spot-webots-cloud
