### ISSUE TITLE
ROS2 bag file replay on the robot in webots

### ISSUE THREAD

**Issue by ToncyChen** [MASKOR/webots_ros2_spot#29]
Recently I have recorded a ros2 bag file recording to the topic `/joint_states` for the spot arm using `moveit_launch.py`. However when I replayed the ros2 bag file, it only showed the arm trajectories moved in `rviz2` window. In the meanwhile, the robot in the webots window didn't move. 
The following is the video about it:
[Screencast from 08-26-2024 04:33:44 PM.webm](https://github.com/user-attachments/assets/6c737981-f48a-48d3-80dc-762617ec679d)
So in this case, did I really replay the ros2 bag file successfully on the robot in simulation environment?
If not, could you guide me how to solve this issue?
Should I record other topics in my ros2 bag file to make the robot in webots window move?

**Comment by skpawar1305** [comment]
record and play "/spotarm_joint_trajectory_controller/joint_trajectory"

**Comment by ToncyChen** [comment]
Do you mean only record `/spotarm_joint_trajectory_controller/joint_trajectory` with ros2 bag file and replay on that?
If so, I have tried. However, according to the "metadata.yaml" it generated, the ros2 bag file didn't actually record any message from `/spotarm_joint_trajectory_controller/joint_trajectory`.

**Comment by skpawar1305** [comment]
how are you moving the arm?
if it's through action, then check in hidden topics, I guess feedback also publishes the joint angles
you need to publish to above topic  to move the arm

**Comment by ToncyChen** [comment]
I move the arm by pulling the globe with coordinate using my mouse when recording the bag file.
[Screencast from 09-21-2024 12:11:58 AM.webm](https://github.com/user-attachments/assets/cf020608-6501-4316-862e-f02d583edd20)
Is this the action you mean?
If not, how should I move the arm correctly?

**Comment by skpawar1305** [comment]
> I move the arm by pulling the globe with coordinate using my mouse when recording the bag file. [Screencast from 09-21-2024 12:11:58 AM.webm](https://github.com/user-attachments/assets/cf020608-6501-4316-862e-f02d583edd20) Is this the action you mean? If not, how should I move the arm correctly?

when you move the arm through Rviz2,
ros2 bag record --include-hidden-topics /spotarm_joint_trajectory_controller/follow_joint_trajectory/_action/feedback
and play this bag file along with following python node:
```
import rclpy
from rclpy.node import Node
from control_msgs.action._follow_joint_trajectory import FollowJointTrajectory_FeedbackMessage
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint
from rclpy.qos import QoSProfile

class TrajectorySubscriberPublisher(Node):
    def __init__(self):
        super().__init__('trajectory_feedback_processor')
        
        self.subscription = self.create_subscription(
            FollowJointTrajectory_FeedbackMessage,
            '/spotarm_joint_trajectory_controller/follow_joint_trajectory/_action/feedback',
            self.feedback_callback,
            1
        )
        
        self.publisher = self.create_publisher(JointTrajectory, '/spotarm_joint_trajectory_controller/joint_trajectory', QoSProfile(depth=10))

    def feedback_callback(self, msg: FollowJointTrajectory_FeedbackMessage):
        new_msg = JointTrajectory()
        new_msg.joint_names = msg.feedback.joint_names

        point = JointTrajectoryPoint()
        point.positions = msg.feedback.actual.positions
        point.velocities = msg.feedback.actual.velocities
        point.accelerations = msg.feedback.actual.accelerations
        point.effort = msg.feedback.actual.effort

        new_msg.points.append(point)
        self.publisher.publish(new_msg)


def main(args=None):
    rclpy.init(args=args)
    rclpy.spin(TrajectorySubscriberPublisher())
    rclpy.shutdown()


if __name__ == '__main__':
    main()

```
