### ISSUE TITLE
[Feature Request/Question] Webots Control

### ISSUE THREAD

**Issue by alecpizz** [MASKOR/webots_ros2_spot#30]
Hello, I am currently using this project to experiment with spot, since Webots doesn't provide any sample code for interacting with spot. My end goal is to make it easy to use for a class, so that students can write a simple python script to interact with the robot, e.g. moveforward(5) makes the robot walk forward for 5 seconds. My main issue is getting students setup with ROS2, as it requires a Ubuntu instance to get going, and all of our machines are Windows. Is there any way to run the walking logic without ROS2? 

Apologies if my wording is unclear. Let me know if there's any other information I can provide.

**Comment by skpawar1305** [comment]
https://github.com/RRL-ALeRT/spot-webots-cloud

**Comment by alecpizz** [comment]
This seems to be perfect for my usecase, thank you so much!
