### ISSUE TITLE
question about changing `spot.urdf` as well as `spot.wbt` 

### ISSUE THREAD

**Issue by justyx404** [MASKOR/webots_ros2_spot#31]
Hi, I would like to remove the SpotArm as well as the kinect. Move the LiDAR to the [frontExtension](https://github.com/MASKOR/webots_ros2_spot/blob/48b5343188321c99d526f3d654a666f6a31b8499/worlds/spot.wbt#L358), I wonder how to adjust the [spot.urdf](https://github.com/MASKOR/webots_ros2_spot/blob/main/resource/spot.urdf) file accordingly to make sure the transformation is still correct?

**Comment by skpawar1305** [comment]
pause and reset the simulation time to 0.
do the changes to the robot, right click on it and export as urdf.
then this
https://github.com/MASKOR/webots_ros2_spot/commit/864724feb0f4d9d8d0972e8b8ed140dce01b5271
