### ISSUE TITLE
Spot arm cannot move

### ISSUE THREAD

**Issue by ToncyChen** [MASKOR/webots_ros2_spot#36]
Hi,

Recently, I have some problem with repository "webots_ros2_spot" in my local laptop. When I launched the file `spot_launch.py`, after the webots window showed up, the Spot's arm didn't retract. And I could not use the Moveit2 to move the arm, either.
The following picture is the error message when I launched the file `spot_launch.py`:
![Screenshot from 2024-12-15 02-47-15](https://github.com/user-attachments/assets/1ac3f4f4-1ecb-42e5-b370-729d859268eb)
I even created another workspace and cloned the same repository again to test. However, the result seemed to be the same.

Could you guide me how to solve this problem?

**Comment by skpawar1305** [comment]
https://github.com/cyberbotics/webots_ros2/pull/1011
